name: "Merge Pull Requests"

description: "Run merge-pulls to automate the pull request merging"

author: tagdots

branding:
  icon: git-pull-request
  color: green

inputs:
  base-branch:
    description: "The destination git branch where your changes are merged"
    default: "main"
    required: false

  dry-run:
    description: "Preview mode: true = show what would be merged, false = perform actual merge"
    default: "true"
    required: false

  bypass-review-count:
    description: "Bypass review count requirement"
    default: "false"
    required: false

  exclude-labels:
    description: "Labels to exclude to filter PRs"
    default: ""
    required: false

  include-labels:
    description: "Labels to include to filter PRs"
    default: ""
    required: false

  merge-method:
    description: "Pull request merge strategies: merge, rebase, squash"
    default: "merge"
    required: false

  owner:
    description: "Filter to specific GitHub user/org (leave empty for all)"
    default: ""
    required: false

  prefix:
    description: "Filter PRs by title prefix (case-insensitive, empty = all)"
    default: ""
    required: false

  repo-type:
    description: "Filter repositories by type: all, private, or public"
    default: "all"
    required: false

runs:
  using: "composite"

  steps:
    - name: Checkout source code # https://github.com/marketplace/actions/checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Python # https://github.com/marketplace/actions/setup-python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.14.x"

    - name: Setup UV # https://github.com/marketplace/actions/astral-sh-setup-uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        enable-cache: "true"
        version: "0.12.x"

    - name: Install App
      shell: bash
      run: |
        uv venv
        uv pip install -U merge-pulls

    - name: Show Versions
      shell: bash
      run: |
        echo "Python Version : $(python --version)"
        echo "UV Version     : $(uv --version)"
        echo "App Version    : $(uv run merge-pulls --version)"

    - name: Run App
      shell: bash
      env:
        INPUT_BASE_BRANCH: "${{ inputs.base-branch }}"
        INPUT_BYPASS_REVIEW_COUNT: "${{ inputs.bypass-review-count }}"
        INPUT_DRY_RUN: "${{ inputs.dry-run }}"
        INPUT_EXCLUDE_LABELS: "${{ inputs.exclude-labels }}"
        INPUT_INCLUDE_LABELS: "${{ inputs.include-labels }}"
        INPUT_MERGE_METHOD: "${{ inputs.merge-method }}"
        INPUT_OWNER: "${{ inputs.owner }}"
        INPUT_PREFIX: "${{ inputs.prefix }}"
        INPUT_REPO_TYPE: "${{ inputs.repo-type}}"
      run: |
        # run app
        COLUMNS=145 uv run merge-pulls \
            --base-branch "$INPUT_BASE_BRANCH" \
            --bypass-review-count "$INPUT_BYPASS_REVIEW_COUNT" \
            --dry-run "$INPUT_DRY_RUN" \
            --exclude-labels "$INPUT_EXCLUDE_LABELS" \
            --include-labels "$INPUT_INCLUDE_LABELS" \
            --merge-method "$INPUT_MERGE_METHOD" \
            --owner "$INPUT_OWNER" \
            --prefix "$INPUT_PREFIX" \
            --repo-type "$INPUT_REPO_TYPE"
